name: lighthouse

uses: treosh/lighthouse-ci-action@v10
with:
    configPath: ".github/workflows/lighthouserc.json"
    temporaryPublicStorage: true
    uploadArtifacts: true
    runs: 3

on:
    pull_request:
        branches:
            - "**"
    workflow_dispatch:

jobs:
    lighthouse:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Use NodeJS 16.x
              uses: actions/setup-node@v4
              with:
                  node-version: 16.x
            - run: |
                  npm install
                  npm run build
            - name: Run lighthouse
              run: |
                  npm install -g @lhci/cli@0.7.x
                  lhci autorun
